/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TextSteganography;

import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.KeySpec;
import java.util.Base64;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadi
 */
public class Text_Decryption extends javax.swing.JFrame {
        private static final String SECRET_KEY = "123456789";
        private static final String SALTVALUE = "abcdefg";

        public static String decrypt(String strToDecrypt) {
                try {
                        /* Declare a byte array. */
                        byte[] iv = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
                        IvParameterSpec ivspec = new IvParameterSpec(iv);
                        /* Create factory for secret keys. */
                        SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
                        /* PBEKeySpec class implements KeySpec interface. */
                        KeySpec spec = new PBEKeySpec(SECRET_KEY.toCharArray(), SALTVALUE.getBytes(), 65536, 256);
                        SecretKey tmp = factory.generateSecret(spec);
                        SecretKeySpec secretKey = new SecretKeySpec(tmp.getEncoded(), "AES");
                        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
                        cipher.init(Cipher.DECRYPT_MODE, secretKey, ivspec);
                        /* Retruns decrypted value. */
                        return new String(cipher.doFinal(Base64.getDecoder().decode(strToDecrypt)));
                } catch (InvalidAlgorithmParameterException | InvalidKeyException | NoSuchAlgorithmException
                                | InvalidKeySpecException | BadPaddingException | IllegalBlockSizeException
                                | NoSuchPaddingException e) {
                        System.out.println("Error occured during decryption: " + e.toString());
                }
                return null;
        }

        /**
         * Creates new form Text_Decryption
         */
        public Text_Decryption() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                // jTextField1 = new javax.swing.JTextField();
                // jLabel1 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();
                jPanel2 = new javax.swing.JPanel();
                jButton3 = new javax.swing.JButton();
                // jButton2 = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                // jButton4 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jTextArea1.setColumns(20);
                jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
                jTextArea1.setLineWrap(true);
                jTextArea1.setRows(5);
                jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter the Message",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("Tahoma", 1, 12))); // NOI18N
                jScrollPane1.setViewportView(jTextArea1);

                // jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                // jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                // jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                // jLabel1.setText("Enter a number between 1 and 10 : ");

                jTextArea2.setColumns(20);
                jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
                jTextArea2.setLineWrap(true);
                jTextArea2.setRows(5);
                jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Decrypted Message : ",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("Tahoma", 1, 12))); // NOI18N
                jScrollPane2.setViewportView(jTextArea2);

                jPanel2.setBackground(new java.awt.Color(6, 6, 6));

                jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jButton3.setText("Reset");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });
                // jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                // jButton2.setText("Save");

                jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jButton1.setText("Decode");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                // jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                // jButton4.setText("Send");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(181, Short.MAX_VALUE)
                                                                // .addComponent(jButton4,
                                                                //                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                //                 119,
                                                                //                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                // .addGap(18, 18, 18)
                                                                .addComponent(jButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                119,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                // .addComponent(jButton2,
                                                                //                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                //                 131,
                                                                //                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                // .addGap(18, 18, 18)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                131,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(19, 19, 19)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jButton1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                53,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                53,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                // .addComponent(jButton4,
                                                                                                                //                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                //                 53,
                                                                                                                //                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                )
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                // .addComponent(jButton2,
                                                                                //                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                //                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                //                 Short.MAX_VALUE)
                                                                                                )
                                                                .addContainerGap()));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane2,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                // .addComponent(jLabel1,
                                                                                                // javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                // 501,
                                                                                                // javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                // .addPreferredGap(
                                                                                                // javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                // .addComponent(jTextField1)
                                                                                                )
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                .addContainerGap())
                                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                204, Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                // .addComponent(jTextField1,
                                                                                //                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                //                 42,
                                                                                //                 Short.MAX_VALUE)
                                                                                // .addComponent(jLabel1,
                                                                                //                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                //                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                //                 Short.MAX_VALUE)
                                                                                                )
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                224,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                if (jTextArea1.getText().isEmpty() )
                        JOptionPane.showMessageDialog(this, "Please Enter a Message First! ");
                else {
                        String message = jTextArea1.getText();
                        // int pass = Integer.parseInt(jTextField1.getText());
                        // char[] mess = message.toCharArray();

                        // StringBuilder sb = new StringBuilder();
                        // for (char c : mess) {
                        // sb.append(c = (char) (c - pass));
                        // }
                        int l1 = 0, l2 = 0;
                        String first = "";
                        String second = "";
                        // System.out.println(message.length());
                        for (int i = 0; i < message.length(); i++) {
                                if (message.charAt(i) == '~') {
                                        // System.out.println("Inside if");
                                        l1 = i + 1;
                                        l2 = (message.length()) - l1;
                                        break;
                                }
                        }
                        // System.out.println(l1);
                        // System.out.println(l2);
                        for (int i = 0; i < l1 - 1; i++) {
                                first += message.charAt(i);
                        }
                        for (int j = l1; j < message.length(); j++) {
                                second += message.charAt(j);
                        }
                        String newFirst = decrypt(first);
                        String newSecond = decrypt(second);
                        int len1 = newFirst.length();
                        int len2 = newSecond.length();
                        String res = "";
                        int l = Math.max(len1, len2);
                        for (int i = 0; i < l; i++) {
                                if (i < len1)
                                        res += newFirst.charAt(i);
                                if (i < len2)
                                        res += newSecond.charAt(i);
                        }
                        jTextArea2.setText(res);
                }
        }// GEN-LAST:event_jButton1ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//
                jTextArea1.setText("");
                jTextArea2.setText("");
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Text_Decryption.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Text_Decryption.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Text_Decryption.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Text_Decryption.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Text_Decryption().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        // private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        // private javax.swing.JButton jButton4;
        // private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextArea jTextArea2;
        // private javax.swing.JTextField jTextField1;
        // End of variables declaration//GEN-END:variables
}
